### ISSUE TITLE
Support Spark 2.0.x & Scala 2.11.x

### ISSUE THREAD

**Issue by metasim** [LLNL/spark-hdf5#8]
Would like to try this package out--very interested in the capability--but need to work with more recent platform libraries.

**Comment by joshuata** [comment]
Are you having specific issues with running this package under 2.0? The specification in `package.sbt` allows us to guarantee backwards compatibility with the versions we use internally.

That said, I would be willing to release a new major version to support Spark 2.0 if there are backwards incompatible changes.

**Comment by metasim** [comment]
I'm not familiar with the `package.sbt` system.... so I can't say anything about compatibility there. I was interested in using it as a regular compile time dependency, but with 2.0, etc. After the changes in PR #9, all the tests passed and things worked fine as best as I can tell.

**Comment by joshuata** [comment]
I've decided that master should track Spark releases and that there will be a separate branch for backwards compatibility.

Thank you so much for your contributions!
